# Generated by Django 4.2.2 on 2023-07-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MEMBERS', '0003_delete_alum_alter_member_current_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_year',
        ),
    ]
