# Generated by Django 4.2.2 on 2023-07-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField(max_length=50000)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='eventPosters/')),
                ('event_datetime', models.DateTimeField(verbose_name='Date of event : ')),
                ('event_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=15)),
                ('event_starttime', models.DateTimeField(verbose_name='Start Date of the event: ')),
                ('event_endtime', models.DateTimeField(verbose_name='End date of the event: ')),
                ('active', models.BooleanField(default=True, max_length=50000)),
                ('text1', models.CharField(blank=True, max_length=20)),
                ('url1', models.CharField(blank=True, max_length=500)),
                ('text2', models.CharField(blank=True, max_length=20)),
                ('url2', models.CharField(blank=True, max_length=500)),
                ('text3', models.CharField(blank=True, max_length=20)),
                ('url3', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-event_datetime'],
            },
        ),
    ]
