# Generated by Django 4.2.2 on 2023-07-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVENTS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
    ]
