# Generated by Django 4.2.2 on 2023-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEMBERS', '0002_alum_member_delete_alumni_delete_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alum',
        ),
        migrations.AlterField(
            model_name='member',
            name='current_year',
            field=models.CharField(choices=[('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('NA', 'NA')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='passout_year',
            field=models.CharField(default='2017', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
